package ci.sycapay.pispi.service.alias;

import ci.sycapay.pispi.client.AipClient;
import ci.sycapay.pispi.config.PiSpiProperties;
import ci.sycapay.pispi.dto.alias.AliasCreationRequest;
import ci.sycapay.pispi.dto.alias.AliasResponse;
import ci.sycapay.pispi.entity.PiAlias;
import ci.sycapay.pispi.dto.common.ClientInfo;
import ci.sycapay.pispi.enums.*;
import ci.sycapay.pispi.exception.AipCommunicationException;
import ci.sycapay.pispi.exception.DuplicateRequestException;
import ci.sycapay.pispi.exception.InvalidStateException;
import ci.sycapay.pispi.exception.ResourceNotFoundException;
import ci.sycapay.pispi.repository.PiAliasRepository;
import ci.sycapay.pispi.service.MessageLogService;
import ci.sycapay.pispi.util.AliasCodeGenerator;
import ci.sycapay.pispi.util.IdGenerator;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.HttpStatusCodeException;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static ci.sycapay.pispi.util.DateTimeUtil.formatDateTime;

@Slf4j
@Service
@RequiredArgsConstructor
public class AliasService {

    private static final List<AliasStatus> BLOCKING_STATUSES =
            List.of(AliasStatus.ACTIVE, AliasStatus.PENDING);

    private final PiAliasRepository aliasRepository;
    private final AipClient aipClient;
    private final PiSpiProperties properties;
    private final MessageLogService messageLogService;

    @Transactional
    public AliasResponse createAlias(AliasCreationRequest request) {
        String codeMembre = properties.getCodeMembre();
        TypeAlias requestedType = request.getTypeAlias();

        checkDuplicateByAliasValue(request.getAlias(), requestedType);
        checkDuplicateByIdentifiant(request.getClient().getIdentifiant(), requestedType);

        if (requestedType == TypeAlias.MBNO) {
            // MBNO creation also provisions a SHID alias for the same client.
            checkDuplicateByIdentifiant(request.getClient().getIdentifiant(), TypeAlias.SHID);
            return createMbnoWithShid(request, codeMembre);
        }

        return createSingleAlias(request, requestedType, request.getAlias(), codeMembre);
    }

    private AliasResponse createSingleAlias(AliasCreationRequest request,
                                            TypeAlias typeAlias,
                                            String aliasValue,
                                            String codeMembre) {
        String endToEndId = IdGenerator.generateEndToEndId(codeMembre);
        log.info("Creating {} alias with endToEndId: {}", typeAlias, endToEndId);

        PiAlias alias = persistPendingAlias(endToEndId, request, typeAlias, aliasValue, codeMembre);
        sendCreationToAip(alias, buildAliasPayload(endToEndId, request, typeAlias, aliasValue));

        return AliasResponse.builder()
                .endToEndId(endToEndId)
                .statut(StatutOperationAlias.EN_COURS)
                .alias(aliasValue)
                .typeAlias(typeAlias)
                .build();
    }

    /**
     * MBNO creation issues a single request to PI-RAC. PI provisions both an MBNO
     * (value = phone number) and a companion SHID (value generated by PI). We
     * persist both rows locally up front, sharing the request's idCreationAlias,
     * so the creation callback can resolve and activate them together.
     */
    private AliasResponse createMbnoWithShid(AliasCreationRequest request, String codeMembre) {
        String endToEndId = IdGenerator.generateEndToEndId(codeMembre);
        log.info("Creating MBNO+SHID pair for identifiant {} with endToEndId {}",
                request.getClient().getIdentifiant(), endToEndId);

        PiAlias mbnoAlias = persistPendingAlias(
                endToEndId, request, TypeAlias.MBNO, request.getAlias(), codeMembre);
        PiAlias shidAlias = persistPendingAlias(
                endToEndId, request, TypeAlias.SHID, null, codeMembre);

        try {
            sendCreationToAip(mbnoAlias,
                    buildAliasPayload(endToEndId, request, TypeAlias.MBNO, request.getAlias()));
        } catch (AipCommunicationException e) {
            // sendCreationToAip already marked mbnoAlias FAILED; mirror it on the SHID row.
            markFailed(shidAlias);
            throw e;
        }

        return AliasResponse.builder()
                .endToEndId(endToEndId)
                .statut(StatutOperationAlias.EN_COURS)
                .alias(request.getAlias())
                .typeAlias(TypeAlias.MBNO)
                .build();
    }

    private void checkDuplicateByAliasValue(String aliasValue, TypeAlias typeAlias) {
        if (aliasValue == null) return;
        aliasRepository.findByAliasValueAndTypeAliasAndStatutIn(aliasValue, typeAlias, BLOCKING_STATUSES)
                .ifPresent(existing -> {
                    throw new DuplicateRequestException("Alias", aliasValue, existing.getStatut().name());
                });
    }

    private void checkDuplicateByIdentifiant(String identifiant, TypeAlias typeAlias) {
        if (identifiant == null) return;
        aliasRepository.findByIdentifiantAndTypeAliasAndStatutIn(identifiant, typeAlias, BLOCKING_STATUSES)
                .ifPresent(existing -> {
                    throw new DuplicateRequestException(
                            "Alias",
                            identifiant + "/" + typeAlias,
                            existing.getStatut().name());
                });
    }

    private PiAlias persistPendingAlias(String endToEndId,
                                        AliasCreationRequest request,
                                        TypeAlias typeAlias,
                                        String aliasValue,
                                        String codeMembre) {
        ClientInfo c = request.getClient();

        LocalDateTime startOfDay = LocalDate.now().atStartOfDay();
        LocalDateTime endOfDay = LocalDate.now().atTime(LocalTime.MAX);
        long todayCount = aliasRepository.countByCodeMembreParticipantAndCreatedAtBetween(
                codeMembre, startOfDay, endOfDay);
        String codification = AliasCodeGenerator.generate(codeMembre, typeAlias, todayCount);

        PiAlias alias = PiAlias.builder()
                .endToEndId(endToEndId)
                .aliasValue(aliasValue)
                .typeAlias(typeAlias)
                .codification(codification)
                .typeClient(c.getTypeClient())
                .nom(c.getNom())
                .prenom(c.getPrenom())
                .raisonSociale(c.getRaisonSociale())
                .typeIdentifiant(c.getTypeIdentifiant())
                .identifiant(c.getIdentifiant())
                .dateNaissance(c.getDateNaissance() != null ? LocalDate.parse(c.getDateNaissance()) : null)
                .nationalite(c.getNationalite())
                .pays(c.getPays())
                .adresse(c.getAdresse())
                .ville(c.getVille())
                .codePostal(c.getCodePostal())
                .telephone(c.getTelephone())
                .email(c.getEmail())
                .numeroCompte(request.getNumeroCompte())
                .typeCompte(request.getTypeCompte())
                .codeMembreParticipant(codeMembre)
                .statut(AliasStatus.PENDING)
                .build();

        if (request.getMarchand() != null && typeAlias == TypeAlias.MCOD) {
            alias.setCodeMarchand(request.getMarchand().getCodeMarchand());
            alias.setCategorieCodeMarchand(request.getMarchand().getCategorieCodeMarchand());
            alias.setNomMarchand(request.getMarchand().getNomMarchand());
        }

        return aliasRepository.save(alias);
    }

    private void sendCreationToAip(PiAlias alias, Map<String, Object> payload) {
        String endToEndId = alias.getEndToEndId();
        log.info("Sending alias creation payload (type={}, e2e={}): {}",
                alias.getTypeAlias(), endToEndId, payload);
        messageLogService.log(null, endToEndId, IsoMessageType.RAC_CREATE,
                MessageDirection.OUTBOUND, payload, null, null);

        try {
            Map<String, Object> response = aipClient.post("/alias/creation", payload);
            log.info("Alias creation response from AIP (e2e={}): {}", endToEndId, response);
        } catch (AipCommunicationException e) {
            markFailed(alias);

            Throwable cause = e.getCause();
            Integer httpStatus = null;
            String errorBody = e.getMessage();
            if (cause instanceof HttpStatusCodeException httpEx) {
                httpStatus = httpEx.getStatusCode().value();
                errorBody = httpEx.getResponseBodyAsString();
            }
            messageLogService.logError(endToEndId, IsoMessageType.RAC_CREATE,
                    Map.of("aipError", errorBody != null ? errorBody : "unknown"), httpStatus, errorBody);
            throw e;
        }
    }

    private void markFailed(PiAlias alias) {
        alias.setStatut(AliasStatus.FAILED);
        aliasRepository.save(alias);
    }

    @Transactional
    public AliasResponse modifyAlias(AliasCreationRequest request) {
        PiAlias alias = aliasRepository.findByAliasValueAndTypeAliasAndStatut(
                request.getAlias(), request.getTypeAlias(), AliasStatus.ACTIVE)
                .orElseThrow(() -> new ResourceNotFoundException("Alias", request.getAlias()));

        ClientInfo c = request.getClient();
        validateModificationConstraints(alias, c);

        // Mirror the edits onto every ACTIVE alias sharing this identifiant so the
        // MBNO/SHID pair (and any MCOD) stays in lockstep. BCEAO only accepts one
        // modification call and cascades internally; we reflect that locally.
        List<PiAlias> affected = loadClientAliases(alias);
        boolean applyPassport = alias.getTypeIdentifiant() == CodeSystemeIdentification.CCPT
                && c.getIdentifiant() != null;
        for (PiAlias row : affected) {
            applyModifiableFields(row, c, applyPassport);
        }
        aliasRepository.saveAll(affected);

        Map<String, Object> payload = buildModificationPayload(alias, request);
        String endToEndId = alias.getEndToEndId();
        messageLogService.log(null, endToEndId, IsoMessageType.RAC_MODIFY,
                MessageDirection.OUTBOUND, payload, null, null);

        try {
            aipClient.post("/alias/modification", payload);
        } catch (AipCommunicationException e) {
            Throwable cause = e.getCause();
            Integer httpStatus = null;
            String errorBody = e.getMessage();
            if (cause instanceof HttpStatusCodeException httpEx) {
                httpStatus = httpEx.getStatusCode().value();
                errorBody = httpEx.getResponseBodyAsString();
            }
            messageLogService.logError(endToEndId, IsoMessageType.RAC_MODIFY,
                    Map.of("aipError", errorBody != null ? errorBody : "unknown"), httpStatus, errorBody);
            throw e;
        }

        return AliasResponse.builder()
                .endToEndId(endToEndId)
                .statut(StatutOperationAlias.EN_COURS)
                .alias(request.getAlias())
                .typeAlias(request.getTypeAlias())
                .build();
    }

    /**
     * Returns every ACTIVE alias row for this client (same identifiant). Falls back
     * to a singleton list when the alias has no identifiant (TRAL case) so the
     * modification path still works for unidentified clients.
     */
    private List<PiAlias> loadClientAliases(PiAlias primary) {
        if (primary.getIdentifiant() == null) {
            return List.of(primary);
        }
        List<PiAlias> rows = aliasRepository.findAllByIdentifiantAndStatut(
                primary.getIdentifiant(), AliasStatus.ACTIVE);
        return rows.isEmpty() ? List.of(primary) : rows;
    }

    /**
     * Applies only the fields BCEAO's ModificationAlias schema actually accepts:
     * contact details (pays, telephone, email), denominationSociale for B/G clients,
     * and the passport number for CCPT-identified clients. Fields like nom/prenom
     * and account details (numeroCompte, typeCompte) are immutable on PI and are
     * intentionally ignored here to avoid local/remote divergence.
     */
    private void applyModifiableFields(PiAlias target, ClientInfo c, boolean applyPassport) {
        if (c.getPays() != null) target.setPays(c.getPays());
        if (c.getAdresse() != null) target.setAdresse(c.getAdresse());
        if (c.getVille() != null) target.setVille(c.getVille());
        if (c.getCodePostal() != null) target.setCodePostal(c.getCodePostal());
        if (c.getLieuNaissance() != null) target.setLieuNaissance(c.getLieuNaissance());
        if (c.getDateNaissance() != null) target.setDateNaissance(LocalDate.parse(c.getDateNaissance()));
        if (c.getTelephone() != null) target.setTelephone(c.getTelephone());
        if (c.getEmail() != null) target.setEmail(c.getEmail());
        if (c.getRaisonSociale() != null) target.setRaisonSociale(c.getRaisonSociale());
        if (applyPassport) target.setIdentifiant(c.getIdentifiant());
    }

    /**
     * Validates PI-RAC modification constraints:
     * - denominationSociale can only be modified for B and G clients
     * - Identifier type is immutable (no NIDN ↔ CCPT ↔ TXID changes)
     * - Identifier value is only mutable for CCPT (passport renewals)
     */
    private void validateModificationConstraints(PiAlias alias, ClientInfo requestClient) {
        if (requestClient.getRaisonSociale() != null || requestClient.getDenominationSociale() != null) {
            if (alias.getTypeClient() != TypeClient.B && alias.getTypeClient() != TypeClient.G) {
                throw new InvalidStateException(
                        "denominationSociale/raisonSociale can only be modified for type B (business) and G (government) clients");
            }
        }

        if (requestClient.getTypeIdentifiant() != null
                && alias.getTypeIdentifiant() != null
                && requestClient.getTypeIdentifiant() != alias.getTypeIdentifiant()) {
            throw new InvalidStateException(
                    "Cannot change identification type from " + alias.getTypeIdentifiant()
                            + " to " + requestClient.getTypeIdentifiant()
                            + ". Original identification type must be preserved.");
        }

        if (requestClient.getIdentifiant() != null
                && alias.getIdentifiant() != null
                && !requestClient.getIdentifiant().equals(alias.getIdentifiant())
                && alias.getTypeIdentifiant() != CodeSystemeIdentification.CCPT) {
            throw new InvalidStateException(
                    "Identifier value can only be updated for CCPT (passport) clients");
        }
    }

    @Transactional
    public AliasResponse deleteAlias(TypeAlias typeAlias, String aliasValue, CodeRaisonSuppression raisonSuppression) {
        PiAlias alias = aliasRepository.findByAliasValueAndTypeAliasAndStatut(
                        aliasValue, typeAlias, AliasStatus.ACTIVE)
                .orElseThrow(() -> new ResourceNotFoundException("Alias", aliasValue));

        String endToEndId = alias.getEndToEndId();

        Map<String, Object> payload = new HashMap<>();
        payload.put("endToEndId", endToEndId);
        payload.put("alias", aliasValue);
        payload.put("raisonSuppression", raisonSuppression.name());

        messageLogService.log(null, endToEndId, IsoMessageType.RAC_DELETE,
                MessageDirection.OUTBOUND, payload, null, null);
        aipClient.post("/alias/suppression", payload);

        return AliasResponse.builder()
                .endToEndId(endToEndId)
                .statut(StatutOperationAlias.EN_COURS)
                .alias(aliasValue)
                .typeAlias(typeAlias)
                .build();
    }

    public Map<String, Object> searchAlias(String alias) {
        String codeMembre = properties.getCodeMembre();
        String endToEndId = IdGenerator.generateEndToEndId(codeMembre);

        Map<String, Object> payload = new HashMap<>();
        payload.put("endToEndId", endToEndId);
        payload.put("alias", alias);

        messageLogService.log(null, endToEndId, IsoMessageType.RAC_SEARCH, MessageDirection.OUTBOUND, payload, null, null);
        Map<String, Object> response = aipClient.post("/alias/recherche", payload);
        response.putAll(payload);
        return response;
    }

    public Page<AliasResponse> listAliases(Pageable pageable) {
        return aliasRepository.findByCodeMembreParticipantAndStatut(
                properties.getCodeMembre(), AliasStatus.ACTIVE, pageable)
                .map(a -> AliasResponse.builder()
                        .endToEndId(a.getEndToEndId())
                        .codification(a.getCodification())
                        .alias(a.getAliasValue())
                        .typeAlias(a.getTypeAlias())
                        .dateCreation(formatDateTime(a.getDateCreationRac()))
                        .build());
    }

    // ---- AIP payload builders ----

    /**
     * Builds the creation payload matching the interface-participant's Alias DTO.
     * The {@code effectiveType} / {@code effectiveAliasValue} arguments let a single
     * request produce multiple PI-RAC payloads (MBNO + SHID) with the same client
     * and account data but different alias types and values.
     */
    private Map<String, Object> buildAliasPayload(String endToEndId,
                                                  AliasCreationRequest request,
                                                  TypeAlias effectiveType,
                                                  String effectiveAliasValue) {
        ClientInfo c = request.getClient();
        Map<String, Object> payload = new HashMap<>();

        payload.put("idCreationAlias", endToEndId);
        payload.put("typeAlias", effectiveType.name());
        payload.put("nomClient", c.getNom());
        payload.put("categorieClient", c.getTypeClient().name());
        payload.put("telephoneClient", c.getTelephone());
        payload.put("paysResidenceClient", c.getPays());
        payload.put("participant", properties.getCodeMembre());
        // CIE002 is an E-type (electronic money) participant — use 'other', not 'iban' (banks only)
        payload.put("other", request.getNumeroCompte());
        payload.put("typeCompte", request.getTypeCompte().name());
        payload.put("dateOuvertureCompte", request.getDateOuvertureCompte());

        // Alias value: omitted for SHID (AIP generates it), required for MBNO/MCOD.
        if (effectiveAliasValue != null) payload.put("valeurAlias", effectiveAliasValue);

        // Identifier: mapped by type to the correct field
        if (c.getTypeIdentifiant() != null && c.getIdentifiant() != null) {
            switch (c.getTypeIdentifiant()) {
                case NIDN -> payload.put("identificationNationaleClient", c.getIdentifiant());
                case CCPT -> payload.put("numeroPasseport", c.getIdentifiant());
                case TXID -> payload.put("identificationFiscale", c.getIdentifiant());
            }
        }

        // Genre is required for type P and C clients
        if (c.getTypeClient() == TypeClient.P || c.getTypeClient() == TypeClient.C) {
            payload.put("genreClient", c.getGenre() != null ? c.getGenre() : "1");
        } else if (c.getGenre() != null) {
            payload.put("genreClient", c.getGenre());
        }

        // Optional client fields (matching interface-participant Alias DTO field names)
        if (c.getRaisonSociale() != null) payload.put("raisonSociale", c.getRaisonSociale());
        if (c.getDenominationSociale() != null) payload.put("denominationSociale", c.getDenominationSociale());
        if (c.getDateNaissance() != null) payload.put("dateNaissanceClient", c.getDateNaissance());
        if (c.getLieuNaissance() != null) payload.put("villeNaissanceClient", c.getLieuNaissance());
        if (c.getPaysNaissance() != null) payload.put("paysNaissanceClient", c.getPaysNaissance());
        if (c.getNationalite() != null) payload.put("nationaliteClient", c.getNationalite());
        if (c.getAdresse() != null) payload.put("adresseClient", c.getAdresse());
        if (c.getVille() != null) payload.put("villeClient", c.getVille());
        if (c.getEmail() != null) payload.put("emailClient", c.getEmail());
        if (c.getCodePostal() != null) payload.put("codePostaleClient", c.getCodePostal());
        if (request.getPhotoClient() != null) payload.put("photoClient", request.getPhotoClient());

        // preConfirmation is only valid for type B (personne morale) clients
        if (c.getTypeClient() == TypeClient.B && request.getPreConfirmation() != null) {
            payload.put("preConfirmation", request.getPreConfirmation());
        }

        // Merchant fields only carried on the MCOD leg.
        if (request.getMarchand() != null && effectiveType == TypeAlias.MCOD) {
            if (request.getMarchand().getNomMarchand() != null) payload.put("denominationSociale", request.getMarchand().getNomMarchand());
            if (request.getMarchand().getCategorieCodeMarchand() != null) payload.put("codeActivite", request.getMarchand().getCategorieCodeMarchand());
        }

        return payload;
    }

    /**
     * Builds the modification payload matching the AIP's ModificationAlias schema.
     * Only the fields accepted by that schema are sent (not the full creation payload).
     * Respects PI-RAC constraints:
     * - denominationSociale only for B/G clients
     * - numeroPasseport only if alias was created with CCPT
     */
    private Map<String, Object> buildModificationPayload(PiAlias alias, AliasCreationRequest request) {
        ClientInfo c = request.getClient();
        Map<String, Object> payload = new HashMap<>();

        payload.put("alias", request.getAlias());

        if (c.getPays() != null) payload.put("paysResidenceClient", c.getPays());
        if (c.getTelephone() != null) payload.put("telephoneClient", c.getTelephone());
        if (c.getEmail() != null) payload.put("emailClient", c.getEmail());
        if (c.getAdresse() != null) payload.put("adresseClient", c.getAdresse());
        if (c.getVille() != null) payload.put("villeClient", c.getVille());
        if (c.getCodePostal() != null) payload.put("codePostalClient", c.getCodePostal());
        if (c.getLieuNaissance() != null) payload.put("villeNaissanceClient", c.getLieuNaissance());
        if (c.getDateNaissance() != null) payload.put("dateNaissanceClient", c.getDateNaissance());

        // B/G constraint enforced by validateModificationConstraints; safe to pass through.
        if (c.getRaisonSociale() != null) {
            payload.put("denominationSociale", c.getRaisonSociale());
        }

        // Passport update only if alias was originally created with CCPT identification
        if (alias.getTypeIdentifiant() == CodeSystemeIdentification.CCPT && c.getIdentifiant() != null) {
            payload.put("numeroPasseport", c.getIdentifiant());
        }

        if (request.getPhotoClient() != null) payload.put("photoClient", request.getPhotoClient());
        if (request.getPreConfirmation() != null) payload.put("preConfirmation", request.getPreConfirmation());

        return payload;
    }

}
