package ci.sycapay.pispi.enums;

public enum WebhookEventType {
    TRANSFER_RECEIVED, TRANSFER_RESULT,
    VERIFICATION_RECEIVED, VERIFICATION_RESULT,
    RTP_RECEIVED, RTP_RESULT,
    RETURN_REQUEST_RECEIVED, RETURN_RESULT, RETURN_EXECUTED,
    CLAIM_RECEIVED, MESSAGE_REJECTED,
    PI_NOTIFICATION, NOTIFICATION_ACK, GUARANTEE_UPDATED,
    COMPENSATION_REPORT, TRANSACTION_REPORT, INVOICE_RECEIVED,
    // Alias events
    ALIAS_CREATED, ALIAS_MODIFIED, ALIAS_DELETED, ALIAS_FAILED, ALIAS_SEARCH_RESULT,
    ALIAS_LOCKED, ALIAS_UNLOCKED
}
