package ci.sycapay.pispi.dto.alias;

import ci.sycapay.pispi.dto.common.ClientInfo;
import ci.sycapay.pispi.dto.common.MerchantInfo;
import ci.sycapay.pispi.enums.TypeAlias;
import ci.sycapay.pispi.enums.TypeClient;
import ci.sycapay.pispi.enums.TypeCompte;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.validation.Valid;
import jakarta.validation.constraints.AssertTrue;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request DTO for alias creation.
 *
 * Per BCEAO OpenAPI spec:
 * - typeCompte must be one of: CACC, SVGS, LLSV, TRAN (CompteOther schema)
 * - alias is required for MBNO (phone format) and MCOD (2-10 digits), optional for SHID
 * - preConfirmation is only valid for type B (business) clients
 * - marchand info is recommended for type C (commercial) clients
 *
 * Note on TRAL (ClientParticulierSansIdentification):
 * BCEAO spec defines CompteTRAL for persons without identification, requiring only:
 * nom, categorie (P), paysResidence, telephone.
 * However, TRAL is NOT available for EME (établissements de paiement) participants.
 * Only bank participants can create TRAL accounts.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AliasCreationRequest {

    /**
     * Valeur de l'alias.
     * - MBNO: numéro de téléphone au format E.164 UEMOA (obligatoire)
     * - MCOD: code marchand 2-10 chiffres (obligatoire)
     * - SHID: optionnel - PI génère automatiquement
     */
    @Size(max = 50, message = "alias must not exceed 50 characters")
    private String alias;

    /** Type d'alias: SHID, MBNO, MCOD. */
    @NotNull(message = "typeAlias is required")
    private TypeAlias typeAlias;

    /** Informations du client. */
    @Valid
    @NotNull(message = "client is required")
    private ClientInfo client;

    /**
     * Numéro de compte du client.
     * Pour les EME (type E), utiliser le numéro de téléphone (champ 'other' dans l'API BCEAO).
     */
    @NotBlank(message = "numeroCompte is required")
    @Size(max = 34, message = "numeroCompte must not exceed 34 characters")
    private String numeroCompte;

    /**
     * Type de compte.
     * Valeurs acceptées par le schéma CompteOther BCEAO: CACC, SVGS, LLSV, TRAN.
     * Note: TRAL n'est pas dans le schéma CompteOther standard.
     */
    @NotNull(message = "typeCompte is required")
    private TypeCompte typeCompte;

    /**
     * Date d'ouverture du compte au format ISO 8601 (YYYY-MM-DD).
     */
    @NotBlank(message = "dateOuvertureCompte is required")
    @Pattern(regexp = "^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$",
             message = "dateOuvertureCompte must be in format YYYY-MM-DD")
    private String dateOuvertureCompte;

    /** Code agence (optionnel). */
    @Size(max = 20, message = "codeAgence must not exceed 20 characters")
    private String codeAgence;

    /** Nom de l'agence (optionnel). */
    @Size(max = 140, message = "nomAgence must not exceed 140 characters")
    private String nomAgence;

    /**
     * Informations du marchand.
     * Recommandé pour les clients de type C (commercial).
     */
    @Valid
    private MerchantInfo marchand;

    /** Photo du client encodée en Base64 (optionnel). */
    private String photoClient;

    /**
     * Pré-confirmation requise avant finalisation du virement.
     * Uniquement valide pour les clients de type B (business).
     */
    private Boolean preConfirmation;

    // ---- Cross-field validations ----

    /**
     * Validates that alias is provided for MBNO and MCOD types.
     * SHID aliases are auto-generated by PI, so alias is optional.
     */
    @JsonIgnore
    @AssertTrue(message = "alias is required for MBNO and MCOD alias types")
    public boolean isAliasRequiredForType() {
        if (typeAlias == TypeAlias.SHID) {
            return true; // Optional for SHID
        }
        return alias != null && !alias.isBlank();
    }

    /**
     * Validates MBNO alias format (E.164 UEMOA phone number).
     */
    @JsonIgnore
    @AssertTrue(message = "MBNO alias must be E.164 format with UEMOA country code (e.g., +2250707070707)")
    public boolean isMbnoAliasValid() {
        if (typeAlias != TypeAlias.MBNO || alias == null) {
            return true;
        }
        return alias.matches("^\\+(?:223|226|228|229|225|221|227|245)\\d{8,12}$");
    }

    /**
     * Validates MCOD alias format (2-10 digits).
     */
    @JsonIgnore
    @AssertTrue(message = "MCOD alias must be 2-10 digits")
    public boolean isMcodAliasValid() {
        if (typeAlias != TypeAlias.MCOD || alias == null) {
            return true;
        }
        return alias.matches("^\\d{2,10}$");
    }

    /**
     * Validates that typeCompte is appropriate.
     * Per BCEAO OpenAPI, CompteOther accepts: CACC, SVGS, LLSV, TRAN.
     * Note: TRAL (lightweight accounts for persons without ID) is NOT available for EME participants.
     */
    @JsonIgnore
    @AssertTrue(message = "typeCompte must be one of: CACC, SVGS, LLSV, TRAN")
    public boolean isTypeCompteValid() {
        if (typeCompte == null) {
            return true; // Let @NotNull handle this
        }
        return typeCompte == TypeCompte.CACC ||
               typeCompte == TypeCompte.SVGS ||
               typeCompte == TypeCompte.LLSV ||
               typeCompte == TypeCompte.TRAN;
    }

    /**
     * Validates that identification is always provided.
     * Note: TRAL accounts (persons without ID) are NOT available for EME participants.
     */
    @JsonIgnore
    @AssertTrue(message = "typeIdentifiant and identifiant are required")
    public boolean isIdentificationRequired() {
        return client != null
               && client.getTypeIdentifiant() != null
               && client.getIdentifiant() != null
               && !client.getIdentifiant().isBlank();
    }

    /**
     * Validates that preConfirmation is only set for type B (business) clients.
     */
    @JsonIgnore
    @AssertTrue(message = "preConfirmation is only valid for type B (business) clients")
    public boolean isPreConfirmationValidForClientType() {
        if (preConfirmation == null || !preConfirmation) {
            return true; // Not set or false, no validation needed
        }
        return client != null && client.getTypeClient() == TypeClient.B;
    }

    /**
     * Validates that MBNO alias is only created for type P (personne physique) clients.
     */
    @JsonIgnore
    @AssertTrue(message = "MBNO alias can only be created for type P (personne physique) clients")
    public boolean isMbnoOnlyForPersonnePhysique() {
        if (typeAlias != TypeAlias.MBNO) {
            return true;
        }
        return client != null && client.getTypeClient() == TypeClient.P;
    }

    /**
     * Validates that MCOD alias is only created for type B or C clients.
     */
    @JsonIgnore
    @AssertTrue(message = "MCOD alias can only be created for type B (business) or C (commercial) clients")
    public boolean isMcodOnlyForBusinessOrCommercial() {
        if (typeAlias != TypeAlias.MCOD) {
            return true;
        }
        return client != null &&
               (client.getTypeClient() == TypeClient.B || client.getTypeClient() == TypeClient.C);
    }

    /**
     * Validates that marchand info is provided for MCOD aliases.
     */
    @JsonIgnore
    @AssertTrue(message = "marchand info is required for MCOD alias type")
    public boolean isMarchandRequiredForMcod() {
        if (typeAlias != TypeAlias.MCOD) {
            return true;
        }
        return marchand != null;
    }

    // ---- Type P/C required fields ----

    /**
     * Validates that genre is provided for type P and C clients.
     */
    @JsonIgnore
    @AssertTrue(message = "genre is required for type P and C clients")
    public boolean isGenreRequiredForPC() {
        if (client != null && (client.getTypeClient() == TypeClient.P || client.getTypeClient() == TypeClient.C)) {
            return client.getGenre() != null && !client.getGenre().isBlank();
        }
        return true;
    }

    /**
     * Validates that nationalite is provided for all client types.
     * Per BCEAO spec, nationalite is required for P, C, B, and G clients.
     */
    @JsonIgnore
    @AssertTrue(message = "nationalite is required")
    public boolean isNationaliteRequired() {
        return client != null && client.getNationalite() != null && !client.getNationalite().isBlank();
    }

    /**
     * Validates that birth info is provided for type P and C clients.
     * Per BCEAO: dateNaissance, paysNaissance, and villeNaissance are required.
     */
    @JsonIgnore
    @AssertTrue(message = "dateNaissance, paysNaissance, and lieuNaissance are required for type P and C clients")
    public boolean isBirthInfoRequiredForPC() {
        if (client != null && (client.getTypeClient() == TypeClient.P || client.getTypeClient() == TypeClient.C)) {
            return client.getDateNaissance() != null && !client.getDateNaissance().isBlank()
                    && client.getPaysNaissance() != null && !client.getPaysNaissance().isBlank()
                    && client.getLieuNaissance() != null && !client.getLieuNaissance().isBlank();
        }
        return true;
    }

    // ---- Type B/G required fields ----

    /**
     * Validates that denominationSociale is provided for type B and G clients.
     * Per BCEAO spec, denominationSociale is required for ClientEntreprise (B) and ClientGouvernement (G).
     */
    @JsonIgnore
    @AssertTrue(message = "denominationSociale is required for type B (business) and G (government) clients")
    public boolean isDenominationSocialeRequiredForBG() {
        if (client != null && (client.getTypeClient() == TypeClient.B || client.getTypeClient() == TypeClient.G)) {
            return client.getDenominationSociale() != null && !client.getDenominationSociale().isBlank();
        }
        return true;
    }

    /**
     * Validates that ville is provided for type B and G clients.
     * Per BCEAO spec, ville is required for ClientEntreprise (B) and ClientGouvernement (G).
     */
    @JsonIgnore
    @AssertTrue(message = "ville is required for type B (business) and G (government) clients")
    public boolean isVilleRequiredForBG() {
        if (client != null && (client.getTypeClient() == TypeClient.B || client.getTypeClient() == TypeClient.G)) {
            return client.getVille() != null && !client.getVille().isBlank();
        }
        return true;
    }
}
