package ci.sycapay.pispi.dto.alias;

import ci.sycapay.pispi.dto.common.ClientInfo;
import ci.sycapay.pispi.dto.common.MerchantInfo;
import ci.sycapay.pispi.enums.TypeAlias;
import ci.sycapay.pispi.enums.TypeClient;
import ci.sycapay.pispi.enums.TypeCompte;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.validation.Valid;
import jakarta.validation.constraints.AssertTrue;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request DTO for alias creation.
 *
 * Per BCEAO OpenAPI spec:
 * - typeCompte must be one of: CACC, SVGS, LLSV, TRAN (CompteOther schema)
 * - alias is required for MBNO (phone format) and MCOD (2-10 digits), optional for SHID
 * - preConfirmation is only valid for type B (business) clients
 * - marchand info is recommended for type C (commercial) clients
 *
 * Note on TRAL (ClientParticulierSansIdentification):
 * BCEAO spec defines CompteTRAL for persons without identification, requiring only:
 * nom, categorie (P), paysResidence, telephone.
 * However, TRAL is NOT available for EME (établissements de paiement) participants.
 * Only bank participants can create TRAL accounts.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AliasCreationRequest {

    /**
     * Valeur de l'alias.
     * - MBNO: numéro de téléphone au format E.164 UEMOA (obligatoire)
     * - MCOD: code marchand 2-10 chiffres (obligatoire)
     * - SHID: optionnel - PI génère automatiquement
     */
    @Size(max = 50, message = "alias must not exceed 50 characters")
    private String alias;

    /** Type d'alias: SHID, MBNO, MCOD. */
    @NotNull(message = "typeAlias is required")
    private TypeAlias typeAlias;

    /** Informations du client. */
    @Valid
    @NotNull(message = "client is required")
    private ClientInfo client;

    /**
     * Numéro de compte du client.
     * Pour les EME (type E), utiliser le numéro de téléphone (champ 'other' dans l'API BCEAO).
     */
    @NotBlank(message = "numeroCompte is required")
    @Size(max = 34, message = "numeroCompte must not exceed 34 characters")
    private String numeroCompte;

    /**
     * Type de compte.
     * Valeurs acceptées par le schéma CompteOther BCEAO: CACC, SVGS, LLSV, TRAN.
     * Note: TRAL n'est pas dans le schéma CompteOther standard.
     */
    @NotNull(message = "typeCompte is required")
    private TypeCompte typeCompte;

    /**
     * Date d'ouverture du compte au format ISO 8601 (YYYY-MM-DD).
     */
    @NotBlank(message = "dateOuvertureCompte is required")
    @Pattern(regexp = "^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$",
             message = "dateOuvertureCompte must be in format YYYY-MM-DD")
    private String dateOuvertureCompte;

    /** Code agence (optionnel). */
    @Size(max = 20, message = "codeAgence must not exceed 20 characters")
    private String codeAgence;

    /** Nom de l'agence (optionnel). */
    @Size(max = 140, message = "nomAgence must not exceed 140 characters")
    private String nomAgence;

    /**
     * Informations du marchand.
     * Recommandé pour les clients de type C (commercial).
     */
    @Valid
    private MerchantInfo marchand;

    /**
     * Code d'activité NAEMA du client (optionnel, 4 chiffres par convention).
     * BCEAO PI-RAC §2.2.1: champ optionnel applicable à tout type de client.
     * Pour un MCOD, peut aussi être dérivé de {@code marchand.categorieCodeMarchand}
     * mais celui-ci reste le champ canonique pour les autres types.
     */
    @Pattern(regexp = "^\\d{1,10}$", message = "codeActivite must be 1-10 digits")
    @Size(max = 10)
    private String codeActivite;

    /** Catégorie d'entreprise (optionnel). */
    @Size(max = 140)
    private String categorieEntreprise;

    /**
     * URL publique de la photo/logo du client (optionnel).
     * Spec BCEAO §2.2.1: "Lien public du logo d'une entreprise ou d'un marchand
     * ou d'un site ecommerce ou de la photo d'une personne" — doit commencer
     * par {@code https://}.
     */
    @Pattern(regexp = "^https://.*$",
            message = "photoClient must be a public URL starting with https://")
    @Size(max = 500)
    private String photoClient;

    /**
     * Pré-confirmation requise avant finalisation du virement.
     * Uniquement valide pour les clients de type B (business).
     */
    private Boolean preConfirmation;

    // ---- Cross-field validations ----

    /**
     * Validates that alias is provided for MBNO and MCOD types.
     * SHID aliases are auto-generated by PI, so alias is optional.
     */
    @JsonIgnore
    @AssertTrue(message = "alias is required for MBNO and MCOD alias types")
    public boolean isAliasRequiredForType() {
        if (typeAlias == TypeAlias.SHID) {
            return true; // Optional for SHID
        }
        return alias != null && !alias.isBlank();
    }

    /**
     * Validates MBNO alias format (E.164 UEMOA phone number).
     */
    @JsonIgnore
    @AssertTrue(message = "MBNO alias must be E.164 format with UEMOA country code (e.g., +2250707070707)")
    public boolean isMbnoAliasValid() {
        if (typeAlias != TypeAlias.MBNO || alias == null) {
            return true;
        }
        return alias.matches("^\\+(?:223|226|228|229|225|221|227|245)\\d{8,12}$");
    }

    /**
     * Validates MCOD alias format (2-10 digits).
     */
    @JsonIgnore
    @AssertTrue(message = "MCOD alias must be 2-10 digits")
    public boolean isMcodAliasValid() {
        if (typeAlias != TypeAlias.MCOD || alias == null) {
            return true;
        }
        return alias.matches("^\\d{2,10}$");
    }

    /**
     * Validates typeCompte against the BCEAO PI-RAC v3.0.0 allowed set:
     * {@code CACC | SVGS | TRAN | LLSV | VACC | TAXE | TRAL}.
     *
     * <p>v2.0.4 added {@code VACC} (tontines); {@code TRAL} is reserved for banks
     * (participants creating accounts for persons without identification) and is
     * filtered out of most downstream messages by the AIP when the participant
     * is not a bank.
     */
    @JsonIgnore
    @AssertTrue(message = "typeCompte must be one of: CACC, SVGS, TRAN, LLSV, VACC, TAXE, TRAL")
    public boolean isTypeCompteValid() {
        if (typeCompte == null) return true; // Let @NotNull handle it
        return switch (typeCompte) {
            case CACC, SVGS, TRAN, LLSV, VACC, TAXE, TRAL -> true;
        };
    }

    /**
     * Validates identification per BCEAO PI-RAC v2.0.1 / v2.0.2:
     * <ul>
     *   <li>Optional when {@code typeCompte == TRAL} (BCEAO
     *       {@code ClientParticulierSansIdentification}).</li>
     *   <li>Required otherwise — {@code typeIdentifiant} + {@code identifiant}
     *       must both be present.</li>
     * </ul>
     */
    @JsonIgnore
    @AssertTrue(message = "typeIdentifiant and identifiant are required "
            + "(not required only for TRAL accounts)")
    public boolean isIdentificationRequired() {
        if (typeCompte == TypeCompte.TRAL) return true;
        return client != null
               && client.getTypeIdentifiant() != null
               && client.getIdentifiant() != null
               && !client.getIdentifiant().isBlank();
    }

    /**
     * Validates that preConfirmation is only set for type B (business) clients.
     */
    @JsonIgnore
    @AssertTrue(message = "preConfirmation is only valid for type B (business) clients")
    public boolean isPreConfirmationValidForClientType() {
        if (preConfirmation == null || !preConfirmation) {
            return true; // Not set or false, no validation needed
        }
        return client != null && client.getTypeClient() == TypeClient.B;
    }

    /**
     * Validates that MBNO alias is created for a physical person — either a
     * plain {@code P} or a {@code C} (personne physique commerçante per v2.0.2).
     * The spec does not restrict MBNO ownership to type {@code P} only.
     */
    @JsonIgnore
    @AssertTrue(message = "MBNO alias can only be created for physical persons (type P or C)")
    public boolean isMbnoOnlyForPhysicalPerson() {
        if (typeAlias != TypeAlias.MBNO) return true;
        return client != null
               && (client.getTypeClient() == TypeClient.P
                   || client.getTypeClient() == TypeClient.C);
    }

    /**
     * BCEAO PI-RAC §2.1.3: MCOD is reserved for personnes morales (type B —
     * and G for government services). Type C is a physical person, so MCOD
     * is NOT available for them despite v2.0.2 adding C as a client category.
     */
    @JsonIgnore
    @AssertTrue(message = "MCOD alias can only be created for type B (business) or G (government) clients — personnes morales only")
    public boolean isMcodOnlyForLegalEntity() {
        if (typeAlias != TypeAlias.MCOD) return true;
        return client != null
               && (client.getTypeClient() == TypeClient.B
                   || client.getTypeClient() == TypeClient.G);
    }

    /**
     * Validates that marchand info is provided for MCOD aliases.
     */
    @JsonIgnore
    @AssertTrue(message = "marchand info is required for MCOD alias type")
    public boolean isMarchandRequiredForMcod() {
        if (typeAlias != TypeAlias.MCOD) {
            return true;
        }
        return marchand != null;
    }

    // ---- Type P/C required fields ----

    /**
     * Validates that genre is provided for type P and C clients.
     */
    @JsonIgnore
    @AssertTrue(message = "genre is required for type P and C clients")
    public boolean isGenreRequiredForPC() {
        if (client != null && (client.getTypeClient() == TypeClient.P || client.getTypeClient() == TypeClient.C)) {
            return client.getGenre() != null && !client.getGenre().isBlank();
        }
        return true;
    }

    /**
     * Validates that nationalite is provided for all client types.
     * Per BCEAO spec, nationalite is required for P, C, B, and G clients.
     */
    @JsonIgnore
    @AssertTrue(message = "nationalite is required")
    public boolean isNationaliteRequired() {
        return client != null && client.getNationalite() != null && !client.getNationalite().isBlank();
    }

    /**
     * Per BCEAO PI-RAC v2.0.1, birth info (dateNaissance + paysNaissance +
     * villeNaissance) is required <b>for banks</b> only; it is optional for
     * other participant types (EMEs, SFDs). However, when any of the three is
     * provided, <b>all three must be provided together</b> because they form
     * the ISO 20022 {@code DtAndPlcOfBirth} block that the AIP splits atomically.
     *
     * <p>The service layer already blocks the EME-specific case (birth info
     * absent) via its own checks where required; this DTO just enforces
     * "all-or-nothing" consistency.
     */
    @JsonIgnore
    @AssertTrue(message = "dateNaissance, paysNaissance, and lieuNaissance must be provided together (all three or none)")
    public boolean isBirthInfoConsistent() {
        if (client == null) return true;
        boolean d = client.getDateNaissance() != null && !client.getDateNaissance().isBlank();
        boolean p = client.getPaysNaissance() != null && !client.getPaysNaissance().isBlank();
        boolean l = client.getLieuNaissance() != null && !client.getLieuNaissance().isBlank();
        return (d && p && l) || (!d && !p && !l);
    }

    // ---- Type B/G required fields ----

    /**
     * Validates that denominationSociale is provided for type B and G clients.
     * Per BCEAO spec, denominationSociale is required for ClientEntreprise (B) and ClientGouvernement (G).
     */
    @JsonIgnore
    @AssertTrue(message = "denominationSociale is required for type B (business) and G (government) clients")
    public boolean isDenominationSocialeRequiredForBG() {
        if (client != null && (client.getTypeClient() == TypeClient.B || client.getTypeClient() == TypeClient.G)) {
            return client.getDenominationSociale() != null && !client.getDenominationSociale().isBlank();
        }
        return true;
    }

    /**
     * Validates that ville is provided for type B, G, and C clients.
     * Per BCEAO spec:
     * - v2.0.0: ville is required for personnes morales (B, G)
     * - v2.0.3: ville is also required for personnes physiques commerçantes (C)
     */
    @JsonIgnore
    @AssertTrue(message = "ville is required for type B (business), G (government), and C (commercial) clients")
    public boolean isVilleRequiredForBGC() {
        if (client != null
                && (client.getTypeClient() == TypeClient.B
                    || client.getTypeClient() == TypeClient.G
                    || client.getTypeClient() == TypeClient.C)) {
            return client.getVille() != null && !client.getVille().isBlank();
        }
        return true;
    }

    /**
     * BCEAO PI-RAC v2.0.1: raisonSociale is required for type B (business).
     * G (government) also carries raisonSociale in practice though the spec
     * leaves some ambiguity — we require it for B to match the explicit rule.
     */
    @JsonIgnore
    @AssertTrue(message = "raisonSociale is required for type B (business) clients")
    public boolean isRaisonSocialeRequiredForB() {
        if (client != null && client.getTypeClient() == TypeClient.B) {
            return client.getRaisonSociale() != null && !client.getRaisonSociale().isBlank();
        }
        return true;
    }

    /**
     * BCEAO PI-RAC §2.2.1 (table row "Identification Fiscale"): identification
     * fiscale is marked <b>Obligatoire</b> for entreprises (B). Government
     * entities (G) also register with a tax ID in practice; we only enforce
     * for B strictly per the spec wording.
     */
    @JsonIgnore
    @AssertTrue(message = "identification fiscale (typeIdentifiant=TXID + identifiant) is required for type B (business)")
    public boolean isIdentificationFiscaleRequiredForB() {
        if (client == null || client.getTypeClient() != TypeClient.B) return true;
        if (client.getTypeIdentifiant() == null) return false;
        // For B clients, typeIdentifiant must be TXID (CodeSystemeIdentification enum).
        return "TXID".equals(client.getTypeIdentifiant().name())
               && client.getIdentifiant() != null
               && !client.getIdentifiant().isBlank();
    }
}
