package ci.sycapay.pispi.util;

import ci.sycapay.pispi.enums.TypeAlias;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Generates the internal alias codification used to uniquely identify each alias
 * created by this PI within the SYCAPAY system.
 *
 * Format: {CODE_MEMBRE}-{TYPE_CODE}-{YYYYMMDD}-{SEQ5}
 * Example: CIE002-MB-20260422-00003
 *
 * TYPE_CODE mapping:
 *   MBNO → MB   (Mobile Number)
 *   SHID → SH   (Shadow ID, generated by PI-RAC)
 *   MCOD → MC   (Merchant Code / QR code)
 *
 * SEQ5 is the global daily sequence for the participant (all alias types combined),
 * zero-padded to 5 digits. It is computed by the caller from the current alias count.
 */
public final class AliasCodeGenerator {

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("yyyyMMdd");

    private AliasCodeGenerator() {}

    public static String generate(String codeMembre, TypeAlias typeAlias, long todayCount) {
        String typeCode = switch (typeAlias) {
            case MBNO -> "MB";
            case SHID -> "SH";
            case MCOD -> "MC";
        };
        String date = LocalDate.now().format(DATE_FMT);
        String seq = String.format("%05d", todayCount + 1);
        return codeMembre + "-" + typeCode + "-" + date + "-" + seq;
    }
}
